import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";
import { buildLineDiff, summarizeDiff, type DiffLine } from "@/lib/workspace-editor";

type ApprovedChange = { id: number; path: string; baseVersion: number; previousContent: string | null; proposedContent: string; riskSummary: string; appliedAt: Date | null; createdAt: Date };

export default function WorkspaceHistoryScreen() {
  const router = useRouter();
  const colors = useColors();
  const params = useLocalSearchParams<{ projectId?: string; projectName?: string }>();
  const projectId = Number(params.projectId);
  const validProject = Number.isInteger(projectId) && projectId > 0;
  const historyQuery = trpc.sensitiveChanges.listApplied.useQuery({ projectId, limit: 50 }, { enabled: validProject, refetchInterval: 10_000 });
  const [expandedId, setExpandedId] = useState<number | null>(null);
  const changes = historyQuery.data ?? [];

  return <ScreenContainer className="px-5" containerClassName="bg-background"><FlatList<ApprovedChange>
    data={changes}
    keyExtractor={(item) => String(item.id)}
    contentContainerStyle={styles.list}
    ListHeaderComponent={<View><View style={styles.topRow}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, { borderColor: colors.border }, pressed && styles.pressed]}><Text style={[styles.backText, { color: colors.primary }]}>← العودة</Text></Pressable><View><Text style={[styles.eyebrow, { color: colors.primary }]}>سجل تدقيق دائم</Text><Text style={[styles.heading, { color: colors.foreground }]}>فروقات معتمدة</Text></View></View><Text style={[styles.projectName, { color: colors.muted }]}>{params.projectName ?? "المشروع"}</Text><View style={[styles.note, { backgroundColor: colors.subtle, borderColor: colors.border }]}><Text style={[styles.noteTitle, { color: colors.foreground }]}>نسخ مطبقة بعد المراجعة الثانوية</Text><Text style={[styles.noteCopy, { color: colors.muted }]}>يعرض السجل لقطة الإصدار السابق والمحتوى الذي طُبق بعد اعتماد المراجعة والتحقق من إصدار الملف.</Text></View><Text style={[styles.section, { color: colors.foreground }]}>الإصدارات المطبقة</Text></View>}
    renderItem={({ item }) => <ApprovedDiffCard change={item} expanded={expandedId === item.id} onToggle={() => setExpandedId((current) => current === item.id ? null : item.id)} colors={colors} />}
    ItemSeparatorComponent={() => <View style={styles.separator} />}
    ListEmptyComponent={!historyQuery.isLoading ? <View style={[styles.empty, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.emptyTitle, { color: colors.foreground }]}>{historyQuery.error ? "تعذر تحميل سجل الفروقات" : "لا توجد إصدارات معتمدة بعد"}</Text><Text style={[styles.emptyCopy, { color: colors.muted }]}>{historyQuery.error ? "تحقق من الاتصال وصلاحية المشروع ثم أعد المحاولة." : "سيظهر هنا أي تعديل حساس يُعتمد ويُطبق بنجاح من خلال المراجعة الثانوية."}</Text></View> : null}
  /></ScreenContainer>;
}

function ApprovedDiffCard({ change, expanded, onToggle, colors }: { change: ApprovedChange; expanded: boolean; onToggle: () => void; colors: ReturnType<typeof useColors> }) {
  const lines = useMemo(() => buildLineDiff(change.previousContent ?? "", change.proposedContent), [change.previousContent, change.proposedContent]);
  const summary = useMemo(() => summarizeDiff(lines), [lines]);
  return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.cardTop}><View style={styles.cardHeading}><Text style={[styles.path, { color: colors.foreground }]}>{change.path}</Text><Text style={[styles.date, { color: colors.muted }]}>{formatDate(change.appliedAt ?? change.createdAt)} · من الإصدار {change.baseVersion}</Text></View><View style={styles.appliedBadge}><Text style={styles.appliedText}>طُبق</Text></View></View><Text style={[styles.risk, { color: colors.muted }]}>مراجعة ثانوية: {change.riskSummary}</Text>{change.previousContent === null ? <Text style={[styles.legacy, { color: colors.warning }]}>لا تتوفر لقطة سابقة لهذا السجل القديم؛ تحفظ اللقطات تلقائياً في الإصدارات الجديدة.</Text> : <View><View style={[styles.summary, { backgroundColor: colors.subtle }]}><Text style={[styles.summaryText, { color: colors.primary }]}>+{summary.added} / −{summary.removed} سطر</Text><Text style={[styles.summaryCaption, { color: colors.muted }]}>فرق الإصدار المعتمد</Text></View><Pressable onPress={onToggle} style={({ pressed }) => [styles.toggle, { borderColor: colors.primary }, pressed && styles.pressed]}><Text style={[styles.toggleText, { color: colors.primary }]}>{expanded ? "إخفاء المقارنة" : "عرض المقارنة"}</Text></Pressable>{expanded ? <ApprovedDiffLines lines={lines} colors={colors} /> : null}</View>}</View>;
}

function ApprovedDiffLines({ lines, colors }: { lines: DiffLine[]; colors: ReturnType<typeof useColors> }) { const visible = lines.slice(0, 160); return <View style={styles.diffBox}>{visible.map((line, index) => <View key={`${index}-${line.content}`} style={[styles.diffRow, { backgroundColor: line.kind === "added" ? "#153A2A" : line.kind === "removed" ? "#40222D" : colors.subtle }]}><Text style={[styles.mark, { color: line.kind === "added" ? "#74E1B0" : line.kind === "removed" ? "#FFACB7" : colors.muted }]}>{line.kind === "added" ? "+" : line.kind === "removed" ? "−" : " "}</Text><Text style={[styles.number, { color: colors.muted }]}>{line.newNumber ?? line.oldNumber ?? ""}</Text><Text selectable style={[styles.content, { color: colors.foreground }]}>{line.content || " "}</Text></View>)}{lines.length > visible.length ? <Text style={[styles.more, { color: colors.muted }]}>يعرض أول 160 سطراً من الفرق لحماية أداء الجهاز.</Text> : null}</View>; }
function formatDate(value: Date) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "غير معروف" : date.toLocaleString("ar"); }

const styles = StyleSheet.create({
  list: { paddingBottom: 42, paddingTop: 18 }, topRow: { alignItems: "flex-start", flexDirection: "row-reverse", justifyContent: "space-between" }, back: { borderRadius: 10, borderWidth: 1, paddingHorizontal: 11, paddingVertical: 8 }, backText: { fontSize: 12, fontWeight: "900" }, eyebrow: { fontSize: 12, fontWeight: "900", textAlign: "right" }, heading: { fontSize: 30, fontWeight: "900", marginTop: 2, textAlign: "right" }, projectName: { fontSize: 13, marginTop: 8, textAlign: "right" }, note: { borderRadius: 18, borderWidth: 1, marginTop: 18, padding: 14 }, noteTitle: { fontSize: 14, fontWeight: "900", textAlign: "right" }, noteCopy: { fontSize: 12, lineHeight: 19, marginTop: 5, textAlign: "right" }, section: { fontSize: 17, fontWeight: "900", marginBottom: 12, marginTop: 22, textAlign: "right" }, card: { borderRadius: 18, borderWidth: 1, padding: 14 }, cardTop: { alignItems: "flex-start", flexDirection: "row-reverse", justifyContent: "space-between" }, cardHeading: { flex: 1, marginLeft: 10 }, path: { fontFamily: "monospace", fontSize: 13, fontWeight: "900", textAlign: "left" }, date: { fontSize: 11, marginTop: 5, textAlign: "right" }, appliedBadge: { backgroundColor: "#153A2A", borderRadius: 99, paddingHorizontal: 9, paddingVertical: 5 }, appliedText: { color: "#74E1B0", fontSize: 10, fontWeight: "900" }, risk: { fontSize: 11, lineHeight: 17, marginTop: 10, textAlign: "right" }, legacy: { fontSize: 11, lineHeight: 18, marginTop: 10, textAlign: "right" }, summary: { alignItems: "center", borderRadius: 11, flexDirection: "row-reverse", justifyContent: "space-between", marginTop: 12, padding: 10 }, summaryText: { fontSize: 12, fontWeight: "900" }, summaryCaption: { fontSize: 11 }, toggle: { alignItems: "center", borderRadius: 10, borderWidth: 1, marginTop: 10, paddingVertical: 9 }, toggleText: { fontSize: 12, fontWeight: "900" }, diffBox: { borderRadius: 12, marginTop: 10, overflow: "hidden" }, diffRow: { flexDirection: "row", minHeight: 22, paddingHorizontal: 8, paddingVertical: 2 }, mark: { fontFamily: "monospace", fontSize: 12, width: 16 }, number: { fontFamily: "monospace", fontSize: 11, paddingRight: 8, width: 35 }, content: { flex: 1, fontFamily: "monospace", fontSize: 12, lineHeight: 18, textAlign: "left" }, more: { fontSize: 11, marginTop: 8, textAlign: "right" }, separator: { height: 10 }, empty: { borderRadius: 17, borderWidth: 1, padding: 18 }, emptyTitle: { fontSize: 14, fontWeight: "900", textAlign: "right" }, emptyCopy: { fontSize: 12, lineHeight: 19, marginTop: 5, textAlign: "right" }, pressed: { opacity: 0.75, transform: [{ scale: 0.99 }] },
});
